version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - |
        if [ -f /tmp/yum_save_tx.2024-06-22.02-05.6n9Vi3.yumtx ]; then
          ls -l /tmp/yum_save_tx.2024-06-22.02-05.6n9Vi3.yumtx
        else
          echo "Transaction file not found, skipping transaction load."
        fi
      - sudo yum clean all
      - sudo rm -rf /var/cache/yum
      - sudo rpm --rebuilddb
      - sudo yum clean all       # Clean yum cache
      - sudo yum makecache       # Rebuild yum metadata cache
      - sudo yum update 
      - sudo amazon-linux-extras install nginx1.12
    commands:
      - echo build started on $(date) 
      - ls -l index.html    # Check if index.html exists and verify its permissions
      - ls -ld /var/www/html    # Check permissions and existence of /var/www/html directory
      - sudo cp index.html /var/www/html || echo "Failed to copy index.html to /var/www/html"

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'
