version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo yum update -y   # Update packages before installation
      - sudo amazon-linux-extras install -y nginx1.12   # Install NGINX 1.12
      - sudo /usr/sbin/nginx
    commands:
      - echo build started on $(date) 
      - ls -l index.html    # Check if index.html exists and verify its permissions
      - ls -ld /var/www/html    # Check permissions and existence of /var/www/html directory
      - sudo cp index.html /var/www/html || echo "Failed to copy index.html to /var/www/html"

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'
